version: "3.7"
services:
  delivery-partner:
    image: delivery-partner
    build:
      context: .
    volumes:
      - ".:/app"
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=delivery_partner
      - LENIENT_ASSERTIONS=true
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgis/postgis:12-master
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

networks:
  default:
    external:
      name: local-network
